# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OptionData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OptionChainList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OptionChainList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOptionChainList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OptionChainList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OptionChainList
    def Chains(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from OptionData.OptionChain import OptionChain
            obj = OptionChain()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OptionChainList
    def ChainsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OptionChainList
    def ChainsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def OptionChainListStart(builder):
    builder.StartObject(1)

def Start(builder):
    OptionChainListStart(builder)

def OptionChainListAddChains(builder, chains):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(chains), 0)

def AddChains(builder, chains):
    OptionChainListAddChains(builder, chains)

def OptionChainListStartChainsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChainsVector(builder, numElems):
    return OptionChainListStartChainsVector(builder, numElems)

def OptionChainListEnd(builder):
    return builder.EndObject()

def End(builder):
    return OptionChainListEnd(builder)
